### ISSUE TITLE
broken- won't download anything

### ISSUE THREAD

**Issue by fsiler** [notcammy/PyInstaStories#40]
```
➜  PyInstaStories git:(master) ✗ python3 pyinstastories.py --download nbc             
----------------------------------------------------------------------
[I] PYINSTASTORIES (SCRIPT V2.6 - PYTHON V3.7.7) - 09:04:04 PM
----------------------------------------------------------------------
[I] Using cached login cookie for "XXXXX".
[I] Login to "XXXXX" OK!
[I] Login cookie expiry date: 2020-09-14 at 09:00:34 PM
----------------------------------------------------------------------
Traceback (most recent call last):
  File "pyinstastories.py", line 487, in <module>
    start()
  File "pyinstastories.py", line 428, in start
    if os.path.isdir(args.output):
  File "/Users/fms/Documents/build/brew/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/genericpath.py", line 42, in isdir
    st = os.stat(s)
TypeError: stat: path should be string, bytes, os.PathLike or integer, not NoneType
```

**Comment by fsiler** [comment]
Fixed in part by [PR](https://github.com/dvingerh/PyInstaStories/pull/41)
