### ISSUE TITLE
login error "NoneType"

### ISSUE THREAD

**Issue by Andy8r0X** [notcammy/PyInstaStories#49]
```
D:\>python pyinstastories.py -u id -p pw -d nasa
----------------------------------------------------------------------
[I] PYINSTASTORIES (SCRIPT V2.6 - PYTHON V3.5.4) - 05:37:51 PM
----------------------------------------------------------------------
[W] Unable to find auth cookie file: credentials.json (creating a new one...)
[I] New auth cookie file was made: credentials.json
Traceback (most recent call last):
  File "pyinstastories.py", line 487, in <module>
    start()
  File "pyinstastories.py", line 415, in start
    ig_client = login(args.username, args.password)
  File "pyinstastories.py", line 121, in login
    print('[I] Login to "' + api.authenticated_user_name + '" OK!')
TypeError: Can't convert 'NoneType' object to str implicitly
```
```
----------------------------------------------------------------------
[I] PYINSTASTORIES (SCRIPT V2.6 - PYTHON V3.5.4) - 05:38:02 PM
----------------------------------------------------------------------
[E] Unexpected Exception: Can't convert 'NoneType' object to str implicitly
----------------------------------------------------------------------
```

**Comment by Andy8r0X** [comment]
Solution: Chage authenticated_user_name to authenticated_user_id
Line 84 and Line 121

**Comment by Alexo88** [comment]
> Solution: Chage authenticated_user_name to authenticated_user_id
> Line 84 and Line 121

ty ty you save me,
